version: '3.8'
services:
  rustup:
    build:
      context: .
      dockerfile: .Dockerfile
    env_file:
      - .env
    tty: true
    restart: "no"
    links:
      - dogecoin-core
    ports:
      - 8080:80
    volumes:
      - ./wonky_ord_data:/data
      - ./wonky_ord_data_index:/data_index
      - ./subsidies.json:/data/subsidies.json
      - ./starting_sats.json:/data/starting_sats.json
      - /app/dogecoin-node/volume:/root/.dogecoin:ro
